# Default values for postgres-backup-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gavt45/postgres-backup-s3
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: false
  # runAsNonRoot: true
  # runAsUser: 101

backup:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 7
  postgres:
    database: "db"
    host: "localhost"
    port: 5432
  s3:
    bucket: "backups"
    prefix: "pg-backups"
    endpoint: "https://ams3.digitaloceanspaces.com"
    backup_keep_days: 7

secrets:
  backup:
    postgres:
      user: postgres
      password: postgres
    s3:
      s3Access: asd
      s3Secret: asd
      encryptionPassphrase: asdasdasdasdasddassdadasdasd


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 1024Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
