apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-backup-k8s.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-backup-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresUser: {{ .Values.secrets.backup.postgres.user | quote }}
  postgresPassword: {{ .Values.secrets.backup.postgres.password | quote }}
  postgresDatabase: {{ .Values.backup.postgres.database | quote }}
  s3Access: {{ .Values.secrets.backup.s3.s3Access | quote }}
  s3Secret: {{ .Values.secrets.backup.s3.s3Secret | quote }}
  encryptionPassphrase: {{ .Values.secrets.backup.s3.encryptionPassphrase | quote }}